// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN908SMcyhrIHuTjZ6iMfuO-fb2YKwLp8',
    appId: '1:554642395466:web:7d5f8c4d621316c15c31b3',
    messagingSenderId: '554642395466',
    projectId: 'uchef-83951',
    authDomain: 'uchef-83951.firebaseapp.com',
    storageBucket: 'uchef-83951.appspot.com',
    measurementId: 'G-HR8WFHVR7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3HcLSdERqXkssMWCeYZ84gsqJUGgiOO0',
    appId: '1:554642395466:android:a0a3d37ad81c70065c31b3',
    messagingSenderId: '554642395466',
    projectId: 'uchef-83951',
    storageBucket: 'uchef-83951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo_At1bL5zC-tF1yN2uOKEtBEAmGOx0BQ',
    appId: '1:554642395466:ios:6e2378cd03bc194a5c31b3',
    messagingSenderId: '554642395466',
    projectId: 'uchef-83951',
    storageBucket: 'uchef-83951.appspot.com',
    iosBundleId: 'com.example.uchef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo_At1bL5zC-tF1yN2uOKEtBEAmGOx0BQ',
    appId: '1:554642395466:ios:6e2378cd03bc194a5c31b3',
    messagingSenderId: '554642395466',
    projectId: 'uchef-83951',
    storageBucket: 'uchef-83951.appspot.com',
    iosBundleId: 'com.example.uchef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN908SMcyhrIHuTjZ6iMfuO-fb2YKwLp8',
    appId: '1:554642395466:web:5a48a2f88212397d5c31b3',
    messagingSenderId: '554642395466',
    projectId: 'uchef-83951',
    authDomain: 'uchef-83951.firebaseapp.com',
    storageBucket: 'uchef-83951.appspot.com',
    measurementId: 'G-9B0MJ6DTX1',
  );
}
